language: rust

rust:
    - stable
    - beta
    - nightly

sudo: false

script:
    - "travis_wait 30 sleep 1800 &"
    - cargo check --no-default-features
    - cargo check --no-default-features --features utils
    - cargo check --no-default-features --features import
    - cargo check --no-default-features --features names
    - cargo build --verbose --all-features --all
    - cargo test --verbose --all-features --all

os:
    - linux
    - osx

matrix:
    allow_failures:
        - rust: nightly
        - rust: beta
