language: rust

rust:
    - stable
    - beta
    - nightly

sudo: false

script:
    - cargo build --verbose --all-features --all
    - cargo test --verbose --all-features --all

addons:
    apt:
        packages:
            - libgl1-mesa-dev

os:
    - linux

matrix:
    allow_failures:
        - rust: nightly
        - rust: beta
