language: rust
sudo: false
addons:
  apt:
    packages:
      - libgl1-mesa-dev

matrix:
  include:
    - os: osx
      rust: stable
    - os: osx
      rust: nightly
    - os: linux
      rust: stable
    - os: linux
      rust: nightly
