language: rust

rust:
    - stable
    - beta
    - nightly

sudo: false

script:
    - cargo build --verbose --all-features
    - cargo test --verbose --all-features

addons:
    apt:
        packages:
            - libgl1-mesa-dev

os:
    - linux
    - osx

matrix:
    allow_failures:
        - rust: nightly
        - rust: beta
