[package]
name = "gltf"
version = "0.5.0"
authors = ["alteous <alteous@outlook.com>"]
description = "glTF asset loader"
documentation = "https://docs.rs/gltf"
repository = "https://github.com/alteous/gltf"
readme = "README.md"
keywords = ["glTF", "3D", "asset", "model", "scene"]
license = "MIT/Apache-2.0"
include = [
    "**/*.rs",
    "Cargo.toml",
]

[dependencies]
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"

[features]
default = []
KHR_materials_common = []

[[example]]
name = "gltf_display"
path = "examples/display/main.rs"

