[package]
name = "gltf"
version = "0.1.0"
authors = ["Alteous <alteous@outlook.com>"]

[dependencies]
serde = "0.8"
serde_derive = "0.8"
serde_json = "0.8"

[[example]]
name = "box"
path = "examples/box/main.rs"

