[package]
name = "gltf"
version = "0.4.0"
authors = ["alteous <alteous@outlook.com>"]
description = "glTF asset loader"
documentation = "https://docs.rs/gltf"
repository = "https://github.com/alteous/gltf"
readme = "README.md"
keywords = ["glTF", "3D", "asset", "model", "scene"]
license = "MIT/Apache-2.0"
 
[dependencies]
serde = "0.9"
serde_derive = "0.9"
serde_json = "0.9"

