[package]
name = "gltf"
version = "0.6.0"
authors = ["alteous <alteous@outlook.com>"]
description = "glTF asset loader"
documentation = "https://docs.rs/gltf"
repository = "https://github.com/alteous/gltf"
readme = "README.md"
keywords = ["glTF", "3D", "asset", "model", "scene"]
license = "MIT/Apache-2.0"
include = [
    "./gltf_derive",
    "**/*.rs",
    "Cargo.toml",
]

[dev-dependencies]
inflections = "1.1"

[dependencies]
futures = { path = "../futures-rs" }
gltf_derive = { path = "./gltf_derive" }
image = "0.14"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[features]
default = []
extras = []
names = []

[[example]]
name = "gltf_display"
path = "examples/display/main.rs"

